version: '3.5'

services:

  nginx:
    
    container_name: nginx_server
    build: ./nginx
    depends_on:
      - django
    ports:
      - "0.0.0.0:81:80"
    networks:
      - postgres      
    restart: unless-stopped

  django:
    container_name: django
    build: . 
    depends_on: 
      - postgres
    ports: 
      - "8002:8002"
    volumes:
       - ./mysite:/app
    networks:
      - postgres
    restart: unless-stopped
    tty: true

  postgres:
    container_name: postgres_container
    build: ./postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: